import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Play Kalimba',
  description: 'Generated by mirac',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="google" content="notranslate" />
      </head>
      <body className={inter.className + ' h-screen flex flex-col items-center justify-between'}>{children}</body>
    </html>
  )
}
